### PR TITLE
[WIP] Presence for the OC XMPP backend

### PR DESCRIPTION
**Pull request by LEDfan**
close https://github.com/jsxc/jsxc/issues/269
TODO: 
 - [x] broadcast presence when updated 
 - [x] when some one send presence respond with the current presence of the other users
 - [x] do not return the presence of other users when the user set is presence to unavailable
 - [x] add unit tests
 - [ ] add extra option to use mecache instead of DB for storing the presence
 - [x] add integration tests
 - [x] squash commits

### CODE REVIEW

**Comment by LEDfan** [comment]
It looks like I don't get stable8 to work. If we want to use `IDbConnection` in favour of `IDb` because it's deprecated we need to drop stable8 support, because the Mapper of core still uses IDb in stable8....

**Comment by LEDfan** [comment]
@BernhardPosselt any ideas on solving this? I saw in the news app you are using `IDBConnection` but require stabel 8.2 >=. What would you advice for supporting? Thanks.

**Comment by BernhardPosselt** [comment]
Use IDbConnection and drop 8.0 support or support two different versions (its now possible on the app store to upload multiple versions for multiple owncloud releases)

**Comment by sualko** [comment]
We don't have to remove all deprecated stuff as long as it is not removed from core. EOL for 8.0 is end of this year, so I would prefer to support it.

This affects only this branch, am I right?

**Comment by LEDfan** [comment]
@sualko @BernhardPosselt okay thanks than I'll make sure ownCloud 8 still works. We just have to make a compromise between supported versions and deprecated functions. 
I now changed the code to use (deprecated) prepareQuery and `IDb` it should now support stable8.

**Comment by sualko** [comment]
Great news. We just have to keep in mind, that we have to remove those functions, if 8.0 has reached his eol.

**Comment by BernhardPosselt** [comment]
PS: another thing to keep in mind: most deprecations in the appframework were made when we thought there was 8.1, 8.2, 8.3 and 8.4. Somehow 8.3 and 8.4 are now dropped, so the deprecation dates are not really valid anymore. It's a mess :/

**Comment by LEDfan** [comment]
mmmm. I merged this from the command line but Github doens't see it's merged. I probably did something wrong... 

#Merged
https://github.com/owncloud/jsxc.chat/commit/653d612e1a6d09567b58ff530caa2a61aa4d2dd0

**Comment by sualko** [comment]
If you merge manually you have to merge without fast forward (<code>git merge --no-ff</code>). But I don't know why you merge manually at all. Just squash your commits on the pr branch and push it via <code>push -f</code> to it. Afterwards you can merge via web ui.

**Comment by sualko** [comment]
As you merged it, I assume this can go in the next beta release this afternoon?

**Pull request closed without merging**
