### PR TITLE
XMPP backend / client side / part 2

### PR DESCRIPTION
**Pull request by sualko**
I added an internal/external option to admin settings, improved error messages for invalid Bosh configurations and removed the table design.

@LEDfan Please test and merge.

If you update jsxc core, please remind to run <code>bower install</code> to get the emojione lib.

screen shot 2016-01-26 at 15 26 25

### CODE REVIEW

**Comment by LEDfan** [comment]
Great! I just tested it but I can't get it too work. First I had to fill some placeholder data in the XMPP domain and BOSH url fields, because otherwise my browser would complain they are empty.

There appears a green box which indicates that the settings are saved.
But when I refresh JSXC is not bootstrapped. I added a `console.log` to line 233 of `ojsxc.js` but it doesn't log anything to the console. There are some track traces logged:
selectie_263

`jsxc.options.xmpp.url` is also `null`.

**Comment by sualko** [comment]
Try to log out and in again.

> First I had to fill some placeholder data in the XMPP domain and BOSH url fields

Good point, will fix that.

**Comment by LEDfan** [comment]
> Try to log out and in again.

This solves the problem.
Is there any way to force JSXC to reinitialize after saving the settings? Otherwise maybe this could be mentioned with a notification?

 I must say the JSXC is initialized very fast on my VM. Very nice, in my app it took a bit of time to connect to the xmpp server.

**Comment by sualko** [comment]
> Otherwise maybe this could be mentioned with a notification?

I think this is the better solution.

**Comment by sualko** [comment]
@LEDfan I defined a new field "domain", because oc could run under multiple domains and therefore we have to define a "chat domain", otherwise jsxc could get into trouble.

Can you also use <code>OCP\Config::getAppValue ( 'ojsxc', 'domain' )</code> in your code?

**Comment by sualko** [comment]
screen shot 2016-01-27 at 12 27 15

**Comment by LEDfan** [comment]
@sualko are you sure this is necessary? I made the backend so that when talking to user X via 'localhost' the stanza/messages which are send to X always contains `localhost` as host, even when a user Y send a message to X via `owncloud.com`.

**Comment by LEDfan** [comment]
selectie_264
This is running the latest version of this branch, without the domain config set.

**Comment by sualko** [comment]
> are you sure this is necessary? 

No :smiley:. I remove it and merge both pr.

**Pull request merged**
