### PR TITLE
XMPP backend / client side

### PR DESCRIPTION
**Pull request by sualko**
#15

@LEDfan I get an error for <code>/http-bind</code>:
```
No memcache available
```
Is there a way to disable memcache while I am developing, or do I have to install memcache?

# TODO
I would implement the following points:

- [ ] make it possible to enable/disable in admin section (otherwise any other XMPP server can't be used)
- [ ] use jsxc.start

### CODE REVIEW

**Comment by LEDfan** [comment]
> @LEDfan I get an error for /http-bind:

Should be fixed now, was a hard code value for testing.

**Comment by sualko** [comment]
Does your implementation only work on the current oc master? Because I get an internal server error.

```
PHP Fatal error:  Class 'Sabre\\Xml\\Writer' not found in /var/www/apps/ojsxc/lib/http/xmppresponse.php on line 14
```

Maybe related 6e6efb7?

**Comment by LEDfan** [comment]
Yes that commit will break it. We use the Sabre XML library as wrapper for PHP. The inclusion of the autoloader is needed for this.

**Comment by LEDfan** [comment]
@sualko since oC 9.0 sabre/xml is included, so we can use the library inclued in core.

**Comment by sualko** [comment]
I removed the line, because there is no vendor folder.

Any chance for a fallback for oc versions < 9. What is the minimum required 
version for your code?


Am 20. Januar 2016 2:54:04 nachm. schrieb LEDfan <notifications@github.com>:

**Comment by LEDfan** [comment]
Ah okay. There isn't a vendor directory because it's in `.gitignore`. The dependencies can be installed via composer install. This works both for 9.0 and < 9.0. So for now I would leave this as is.

I'll have a look at which server version my codes supports.

**Comment by sualko** [comment]
Hey, I could it running (after increasing the version number). Can you send/receive messages?

Can you add the subscription attribute to the roster items? This would lead to colourful avatars.

```
<item jid='benvolio@example.org'
          name='Benvolio'
          subscription='both'>
```

**Comment by LEDfan** [comment]
Okay will do, but for now there are no presences. The version number must be increased for the database probably. 

What code do you use in `oc-handle.js` for starting the xmpp connection?

**Comment by LEDfan** [comment]
I'm using:
```
/* global OC */
$(document).ready(function () {
	jsxc.options.xmpp.url = OC.generateUrl('apps/ojsxc/http-bind');
	jsxc.start(OC.currentUser + '@' + OC.getHost(), Math.floor(Math.random() * (1000 - 1)) + 1, Math.floor(Math.random() * (1000 - 1)) + 1);
});
```
But when the localStorage is clear (i.e. first time the page is loaded). I also have to call `$("#jsxc_roster").removeClass("jsxc_noConnection");`

**Comment by LEDfan** [comment]
@sualko which git tag should I use for the JSXC submodule with this branch?

**Pull request merged**
