### PR TITLE
 [WIP] First implementation of the ownCloud XMPP Backend (follow-up of #14)

### PR DESCRIPTION
**Pull request by LEDfan**
cc @sualko 

# TODO before this is ready:
 - [x] TODO add some abstraction to stanza handlers
 - [x] TODO use DB mappers which implement te serializable interface
 - [x] TOOD fix Strophe handling messages twice when it's only received ones
 - [ ]  Presence
 - [x] Remove use of \OCP\User
 - [x] check behaviour with multiple trusted_domains
 - [x] unit test request locking
 - [x] integration test request locking (~~via karma?~~, redis can be easily installed on travis)

# TODO before merging to 3.0 beta:
 - [x] make it possible to enable/disable in admin section (otherwise any other XMPP server can't be used) 
 - [x] use `jsxc.start` 
 - [ ] fix some important TODO's and FIXME's
 - [x] make configuration option to use memcache
 - [ ] squash commits

### CODE REVIEW

**Comment by LEDfan** [comment]
Rebased, I'll start to work on this a bit.

**Comment by jancborchardt** [comment]
Awesome! If you need any help, you know the #owncloud-dev IRC channel. :)

**Comment by karlitschek** [comment]
indeed. super cool!

**Comment by LEDfan** [comment]
@sualko when the client sends an IQ stanza, should the DB still be (only once) polled, our should the result be returned immediate?

**Comment by sualko** [comment]
@LEDfan Can you give an example? I do not understand completely what you mean. But I worked hard for you (and of course some other guys) to implement an easy way to start the chat with valid sid and rid. Checkout https://github.com/jsxc/jsxc/commit/ad3c1bc217b1a9e2217df1407bc8d9880df7ecdf and look up <code>jsxc.start</code>. The following snippet should start the chat:

```
jsxc.options.xmpp.url = "Path to server file";
jsxc.start("klaus@domain", "sid", "rid");
```

Please let me know, if you have any issues with this brand new function or any other questions.

**Comment by LEDfan** [comment]
@sualko nice! I tried to checkout the develop branch inside this PR and run grunt, but "strophejs" isn't in the lib directory, so I added it. Looks like the login is working, except the interface isn't working 100%.

**Comment by sualko** [comment]
>  but "strophejs" isn't in the lib directory

You have to run <code>bower install</code> or <code>bower update</code> respectively.

>  the interface isn't working 100%.

Did you also checkout the latest jsxc.chat version in branch develop?

**Comment by LEDfan** [comment]
That makes sense :P

I think the interface is "broken" because I'm running the master version of ownCloud. (9.0.0 pre alpha). I'll try with 8.2.2 tomorrow.

**Comment by sualko** [comment]
No, works also with current oc master (except a minor sidebar bug), but you have to force node-sass to version 3.3.0. I added this part to package.json a minute ago.

screenshot

**Comment by karlitschek** [comment]
This looks really nice!!!

**Comment by LEDfan** [comment]
@sualko I (vagrant :P) have reinstalled my VM, and I merged develop of this repo into this branch. I used "develop" as branch in the jsxc submodule.

I use the following code in `oc-backend.js` :
````
$(document).ready(function () {
	jsxc.options.xmpp.url = "/index.php/apps/ojsxc/http-bind";
	jsxc.start(OC.currentUser + '@' + OC.getHost(),  "");
});
````
Or:
````
$(document).ready(function () {
	jsxc.options.xmpp.url = "/index.php/apps/ojsxc/http-bind";
	jsxc.start(OC.currentUser + '@' + OC.getHost(), Math.floor(Math.random() * (1000 - 1)) + 1, Math.floor(Math.random() * (1000 - 1)) + 1);
});
````
I also cleared localStorage. But I keep getting: 
selectie_250

I'll send you a link to the VM via e-mail.

**Comment by sualko** [comment]
> I also cleared localStorage. But I keep getting: 

Do you have multiple tabs open?

> I'll send you a link to the VM via e-mail.

Would it not be sufficient to commit your latest changes?

**Comment by LEDfan** [comment]
I pushed the changes. I just re-tested I'm not getting the bareJid error any more, but know in the sidebar there is a message "No connection! Relogin".

**Comment by LEDfan** [comment]
I temporally undo the merge of develop, until the .start() works with our http-bind.

 > Can you give an example? 
What I mean is: 
 1. client sends an IQ request for the roster
````
<body rid='897878733' xmlns='http://jabber.org/protocol/httpbind' sid='7862'><iq from='admin@own.dev' to='own.dev' type='get' xmlns='jabber:client' id='1:sendIQ'><query xmlns='http://jabber.org/protocol/disco#info' node='undefined#undefined'/></iq><iq type='get' xmlns='jabber:client' id='2:sendIQ'><query xmlns='jabber:iq:roster'/></iq><iq type='get' to='admin@own.dev' xmlns='jabber:client' id='3:sendIQ'><vCard xmlns='vcard-temp'/></iq></body>
````
2. servers creates/fetches the roster
3. (?) should the server check for new messages in the database?
4. servers responds

**Comment by sualko** [comment]
> (?) should the server check for new messages in the database?

In general there should be as many stanzas in a response as possible, but the [Best Practices for Handling Offline Messages](http://xmpp.org/extensions/xep-0160.html) defines that offline messages should be only delivered after a client goes online. And a client is online after his initial presence stanza, which I send after I received the roster. Long story short, I guess it doesn't matter :-).

**Comment by LEDfan** [comment]
I have added unit and integrations tests for everything except the handlers, since they will change probably.

**Comment by LEDfan** [comment]
I just added the locking of requests to `http-bind` so a already running requests end when a new request is send. I created a DB backend and a memcache backend.

**Comment by LEDfan** [comment]
See it in action:
gifrecord_2016-01-19_175729

Notice that there is a new request to `http-bind` after sending the chat message, and that the last request is stopped.

**Comment by sualko** [comment]
Wow! Looks awesome. I am really impressed.

Today I will test to merge your branch with the current jsxc branch. Do you prefer to commit those changes by yourself (maybe to test some more), should I create a new branch or should I push the changes directly to this branch?

What is your time schedule? Currently I am planing the beta releaise of 3.0 in the next few days, but it would be awesome to include your stuff in this release. So depending on your timetable we could shift it maybe by some weeks.

**Comment by LEDfan** [comment]
Would be great if we can get the `jsxc.start` working :). Maybe it would be the best to merge it in another branch (derived from this) so we can test it better without loosing changes in this branch.

I think releasing this code with 0.3 beta should be OK. Note that currently presence and group chat isn't possible.
I'll add some notes to the first post about merging this branch.

**Comment by LEDfan** [comment]
I merged the branch of @sualko and added a first working code to setup the connection with the xmpp/bosh server.

Please use the branch `develop` for js/jsxc submodule.

**Comment by LEDfan** [comment]
I just found a bug, the first time a user loads ownCloud it looks like it's connected but if you send a message it doesn't arrive at the other user. It looks like JSXC isn't sending the message to the server. (There is no new http-bind request). But he messages are saved in localStorage I think.

**Comment by LEDfan** [comment]
The last commit fixes this bug!

**Comment by LEDfan** [comment]
The code coverage of the files in lib/* is now 100%.

I'll now start working on presence.

**Comment by sualko** [comment]
> after the admin option is added

I will implement this on monday.

**Comment by sualko** [comment]
@LEDfan and I decided to include this pr in 3.0 even if it doesn't contain all features. Therefore we marked it as "experimental".

**Comment by LEDfan** [comment]
So basic chatting is now working. @sualko the messages are also encrypted via OTR right?

@fossxplorer this is ready to test. You can use the following config values in `config.php`:
````
  'ojsxc.use_memcache' => 
  array (
    'locking' => true, // will use a memcache if available (redis, memcached etc)
  ),
  'ojsxc.polling' => 
  array (
    'sleep_time' => 1, // this is the time between polling the DB for new messages
    'max_cycles' => 10, // this is the amount of polling the DB before returning an empty stanza
  ),
````

**Pull request merged**
