### PR TITLE
Fix chat backend for older ownCloud versions

### PR DESCRIPTION
**Pull request by LEDfan**
This is work in progress. Fix jsxc/jsxc#272.

I just removed APCU from travis since I don't get it working. 
Travis is now also testing stable8, stable8.1 and stable8.2 branches of ownCloud.

 TODO:
 - [x] make sure there are no warning or errors after running the tests.
 - [x] remove HHVM since I don't think it's very important and the build just errors.
 - [x] test on `stable8`, `stable8.1`, `stable8.2`, `master`
 - [x] fix bugs on ownCloud stable8
 - [x] disable memlock on stable8
 - [x] {"reqId":"\/NCJCVp9k4csuQMe81FE","remoteAddr":"","app":"PHP","message":"Undefined variable: stanzas at \/home\/travis\/build\/owncloud\/owncloud\/apps\/ojsxc\/lib\/controller\/httpbindcontroller.php#161","level":3,"time":"2016-01-30T05:50:36+00:00"}
 - [x] {"reqId":"\/NCJCVp9k4csuQMe81FE","remoteAddr":"","app":"PHP","message":"Missing argument 1 for OCP\\AppFramework\\Db\\DoesNotExistException::__construct(), called in \/home\/travis\/build\/owncloud\/owncloud\/apps\/ojsxc\/tests\/unit\/controller\/HttpBindControllerTest.php on line 137 and defined at \/home\/travis\/build\/owncloud\/owncloud\/lib\/public\/appframework\/db\/doesnotexistexception.php#39","level":3,"time":"2016-01-30T05:50:36+00:00"}
 - [x] {"reqId":"\/NCJCVp9k4csuQMe81FE","remoteAddr":"","app":"PHP","message":"Undefined variable: msg at \/home\/travis\/build\/owncloud\/owncloud\/lib\/public\/appframework\/db\/doesnotexistexception.php#40","level":3,"time":"2016-01-30T05:50:36+00:00"}
 - [x] {"reqId":"\/NCJCVp9k4csuQMe81FE","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/home\/travis\/build\/owncloud\/owncloud\/apps\/ojsxc\/lib\/controller\/httpbindcontroller.php#185","level":3,"time":"2016-01-30T05:50:36+00:00"}

### CODE REVIEW

**Comment by LEDfan** [comment]
@sualko please let me merge this via the CLI so I can squash the commits. I guess you don't want such commits in the history :P :smile:

**Comment by sualko** [comment]
:+1:

**Comment by LEDfan** [comment]
Finally the tests are running on `stable8`, `stable8.1`, `stable8.2` and `master`! It looks like only `stable8` is failing: 
selectie_266

**Comment by sualko** [comment]
Mh, in oc 8.0 the <code>OC\AppFramework\Db</code> class is very basic and doesn't contain <code>executeQuery</code>. But I think this is no problem, because sooner or later we have to use <code>IDBConnection</code> anyway as <code>OC\AppFramework\Db</code> is deprecated:

```
@deprecated use IDBConnection directly, will be removed in ownCloud 10
```

**Comment by LEDfan** [comment]
I think I fixed all issues with ownCloud 8.0. At least the unit tests and integration tests are running and the roster and chatting is working.
@sualko if travis is working please test it again. (8.1 and 8.2 shouldn't be a problem if we can trust the tests)

I used the IDbConnection where I can, and I just saw we can use IDbConnection for the mappers too. I will change that.

**Comment by LEDfan** [comment]
Everything is done here. :+1:

**Comment by LEDfan** [comment]
I just rebased this PR and will merge if travis is happy.
I'll do the IDbConnection part in another PR.

**Comment by LEDfan** [comment]
Funny, the builds are broken two times (503 on ubuntu mirror) and now it's working again.
@sualko this is okay to merge. What is your policy for merging branches to master?

**Comment by sualko** [comment]
> What is your policy for merging branches to master?

Currently I have no policy for merging. Just merge if you think it is ready.

**Comment by LEDfan** [comment]
@sualko okay :P I wasn't sure.

**Comment by LEDfan** [comment]
@sualko but we should remove merged branches, right?

**Comment by sualko** [comment]
> but we should remove merged branches, right?

Jup

**Comment by LEDfan** [comment]
About the IDb and IDbConnection if we want to support stable8 we still need to use `IDb`. Because the Mapper of stable8 only accepts `IDb`.... https://github.com/owncloud/core/blob/stable8/lib/public/appframework/db/mapper.php#L48

**Pull request merged**
