### PR TITLE
[WIP] First implementation of the ownCloud XMPP Backend

### PR DESCRIPTION
**Pull request by LEDfan**
I temporary forked the jsxc/jsxc.owncloud repo to keep track of my changes. This PR and fork will be removed as soon as the repo is moved to the ownCloud repo. 

 - [x] TODO add some abstraction to stanza handlers
 - [x] TODO use DB mappers which implement te serializable interface
 - [ ]  TODO move checking for two polling request to SESSION
 - [x] TOOD fix Strophe handling messages twice when it's only received ones
 - [ ]  Presence
 - [x] Remove use of \OCP\User
 - [ ] check behaviour with multiple trusted_domains
 - [ ] add checkbox in admin section to use internal chat

cc @sualko @jancborchardt (-plus)

### CODE REVIEW

**Comment by LEDfan** [comment]
@sualko are you okay with adding the sabre/xmp dependency? This makes the XML handling more easy, as you may know at the conf I spend a lot of time parsing the XML via simplemxl and domdocument....

**Comment by sualko** [comment]
Sabre/xml is totally fine. The simplexml seams to be very buggy.

I will add you know to the repositories, because I wait until deepdiver is back from holidays. 

I also will publish a bug fix release maybe on Monday. This is only to inform you.

**Comment by jancborchardt** [comment]
@sualko can you make it possible to open issues here btw? Or should I open them in another repository?

**Comment by sualko** [comment]
Please open them in [jsxc/jsxc](https://github.com/jsxc/jsxc/issues). Maybe we should discuss this practice, but in my current point of view this is the easiest way to collect all issues for jsxc at one place.

**Comment by LEDfan** [comment]
@sualko can you have a look at making a connection to our backend? I always get erros like `jid is null` or something similar.

**Comment by sualko** [comment]
I will check it.

**Comment by LEDfan** [comment]
Great! The best I have is:
````
/**
 * This function is a hack. Please FIXME!
 */
jsxc.options.favicon.enable = false;
jsxc.options.otr.enable = false;
Strophe.getNodeFromJid = function () {
	return OC.currentUser;
};
Strophe.getDomainFromJid = function () {
	return '33.33';
};
function ocInit(){
	localStorage.clear();
	jsxc.storage.setItem('debug', true);
	jsxc.options.set('xmpp', {'url': '/index.php/apps/ojsxc/http-bind'});
	jsxc.xmpp.login(OC.currentUser + '@33.3', 3434, 3443243); // TODO remove the hardcoded values
	jsxc.xmpp.connected();
	jsxc.storage.setItem('debug', true);
}

$(document).ready(function () {
	ocInit();
});

````

But now the Strophe isn't polling...

**Comment by LEDfan** [comment]
Actually it is long-polling but it doesn’t handle the messages.

**Comment by sualko** [comment]
Normally it should be enough, if you execute this commands once and than reload.
```
jsxc.options.set('otr', {enable: false});
jsxc.options.set('xmpp', {'url': '/index.php/apps/ojsxc/http-bind'});
jsxc.storage.setItem('debug', true);
jsxc.storage.setItem('sid', '7862');
jsxc.storage.setItem('rid', '897878733');
```

**Comment by LEDfan** [comment]
Thanks, but I can't get it to work. There are simply no requests send to '/http-bind', and nothing is logged in the browser console.

**Comment by sualko** [comment]
Sorry, try this one: 

```
localStorage.clear()
jsxc.options.set('otr', {enable: false});
jsxc.options.set('xmpp', {'url': '/index.php/apps/ojsxc/http-bind'});
jsxc.storage.setItem('debug', true);
jsxc.storage.setItem('sid', '7862');
jsxc.storage.setItem('rid', '897878733');
jsxc.storage.setItem('lastActivity', (new Date()).getTime());
jsxc.storage.setItem('jid', OC.currentUser + '@33.3');
```

**Comment by LEDfan** [comment]
No problem! I'm very happy that you are willing to help :smiley:

The client new successfully connects to the backend! However chat messages aren't received. This is a correct response for sending a new message, right?
````
<body><message to="admin@33.33" from="test@33.33" type="chat"><body>af</body></message></body>
````

**Comment by LEDfan** [comment]
Mmm strophe.js/jquery logs the received stanza as an empty body: 
selectie_110

**Comment by LEDfan** [comment]
Chrome console displays the XML stanza however.... 
selectie_111

I think it has something to do with the presence. Maybe StropheJS is thinking he shouldn't receive the message because he isn't online?

**Comment by sualko** [comment]
Incoming messages looks like this:
```
<body xmlns="http://jabber.org/protocol/httpbind">
  <message xmlns="jabber:client" from="georg@localhost/11395954601441475563228758" to="klaus@localhost/10705725741441475541495758" type="chat" id="1441475584282-msg">
    <body>Hello</body>
  </message>
</body>
```

An empty response from the server (on the end of a long poll) looks like this:
```
<body xmlns="http://jabber.org/protocol/httpbind"/>
```

> Maybe StropheJS is thinking he shouldn't receive the message because he isn't online?

This should be no problem for strophe. I think you only missed the namespace. I will test your implementation tomorrow.

**Comment by LEDfan** [comment]
Yes! It's working! Thanks @sualko 
selectie_112

**Comment by sualko** [comment]
Congratulations. Great work.

**Comment by LEDfan** [comment]
selectie_113
:fireworks:

**Comment by sualko** [comment]
How are you doing?

As you can see, we moved to the owncloud orga. :+1:

**Comment by jancborchardt** [comment]
@LEDfan @sualko @DeepDiver1975 Nice! So should we rename this to »chat« and move the current app to »chat-legacy« or something like that?

**Comment by karlitschek** [comment]
i don't think we necessarily have to rename the repo as long as the app has a nice user facing name.

**Comment by sualko** [comment]
For me we could rename both. It would be nice if there would occur jsxc in it, but this is not necessary.

Suggestions?

**Comment by karlitschek** [comment]
Let's keep the repo name of the other chat app as it is. No need to rename stuff around. This repository can be renamed. Something like 'jsxc.chat' maybe? Or only 'jsxc'? The 'owncloud' is redundant here

**Comment by sualko** [comment]
I prefer "jsxc.chat", because otherwise the risk of confusion to the core repo is to high in my point of view.

**Comment by karlitschek** [comment]
O.K. renamed!

**Comment by LEDfan** [comment]
Very nice :+1: Like I said at the conf,my academic year has just started, so I afraid I won't have much time to work on this....  I hope I still can make it happen though

**Comment by sualko** [comment]
@LEDfan can you move the branch to this repo, so maybe others can continue your work.

**Comment by LEDfan** [comment]
@sualko yes of course. I'll do this now.

**Pull request closed without merging**
